version: "3.9" 
services:

  jaeger:
    image: jaegertracing/all-in-one:1.9
    ports:
      # - "5775:5775/udp"
      # - "5778:5778"
      # - "6831:6831/udp"
      # - "6832:6832/udp"
      # - "9411:9411"
      # - "14268:14268"
      - "16686:16686"

  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"

  # prometheus:
  #   image: prom/prometheus:v2.31.0
  #   volumes:
  #     - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"            

  back-end:
    build: 
      dockerfile: ./Dockerfile
      context: ./back-end 
    ports:
      - "8080:80"
    depends_on:
      - jaeger
      - zipkin

  payment-gateway:
    build: 
      dockerfile: ./Dockerfile
      context: ./payment-gateway 
    depends_on:
      - jaeger
      - zipkin

  paypal:
    build: 
      dockerfile: ./Dockerfile
      context: ./paypal
    depends_on:
      - jaeger
      - zipkin

  credit:
    build: 
      dockerfile: ./Dockerfile
      context: ./credit
    depends_on:
      - jaeger
      - zipkin

  shipping-gateway:
    build: 
      dockerfile: ./Dockerfile
      context: ./shipping-gateway 
    depends_on:
      - jaeger
      - zipkin

  toll:
    build: ./toll
    depends_on:
      - jaeger
      - zipkin

  fedex:
    build: ./fedex
    depends_on:
      - jaeger
      - zipkin

  dhl:
    build: ./dhl
    depends_on:
      - jaeger
      - zipkin

  simulator:
    build: 
      dockerfile: ./Dockerfile
      context: ./simulator 
    depends_on:
      - back-end

