version: "3.9"  # optional since v1.27.0
services:

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.9
    container_name: jaeger-tracing
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      # - "9411:9411"
      - "14268:14268"
      - "16686:16686"

  # jaeger:
  #   build: ./jaeger
  #   depends_on:
  #     - jaeger-tracing


  zipkin-collector:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"

  back-end:
    build: 
      dockerfile: ./Dockerfile
      context: ./back-end 
    ports:
      - "8080:80"
    # command:
    #   - "/bin/sh"
    #   - "-c"
    #   - "while ! nc -w 1 -z zipkin-collector 9411; do echo sleep for 1s waiting for zipkin-collector to become available; sleep 1; done && /go/bin/main"
    depends_on:
      - jaeger-tracing
      - zipkin-collector

  payment-gateway:
    build: 
      dockerfile: ./Dockerfile
      context: ./payment-gateway 
    depends_on:
      - jaeger-tracing
      - zipkin-collector

  simulator:
    build: 
      dockerfile: ./Dockerfile
      context: ./simulator 
    depends_on:
      - jaeger-tracing
      - zipkin-collector
      - back-end

